fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Route de connexion au Backoffice
fos_admin_user_security_login:
    path: /login
    defaults: { _controller: FOSUserBundle:Security:login }

# Route de vérification de connexion au Backoffice
fos_admin_user_security_check:
    path:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    requirements:
        _method: POST

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

# Route de déconnexion du Backoffice
fos_admin_user_security_logout:
    path:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
